export default {
    //Countries
    ca: 'Canada',
    usa: 'United States',
    
    //CA Provinces
    ab: 'Alberta',
    bc: 'Colombie-Britannique',
    mb: 'Manitoba',
    nb: 'Nouveau-Brunswick',
    nl: 'Terre-Neuve-et-Labrador',
    ns: 'Nouvelle-Écosse',
    nt: 'Territoires du Nord-Ouest',
    nu: 'Nunavut',
    on: 'Ontario',
    pe: 'Île-du-Prince-Édouard',
    qc: 'Québec',
    sk: 'Saskatchewan',
    yt: 'Yukon',

    //US States
    al: 'Alabama',
    ak: 'Alaska',
    az: 'Arizona',
    ar: 'Arkansas',
    cal: 'California',
    co: 'Colorado',
    ct: 'Connecticut',
    de: 'Delaware',
    dc: 'District of Columbia',
    fl: 'Florida',
    ga: 'Georgia',
    hi: 'Hawaii',
    id: 'Idaho',
    il: 'Illinois',
    in: 'Indiana',
    ia: 'Iowa',
    ks: 'Kansas',
    ky: 'Kentucky',
    la: 'Louisiana',
    me: 'Maine',
    md: 'Maryland',
    ma: 'Massachussets',
    mi: 'Michigan',
    mn: 'Minnesota',
    ms: 'Mississippi',
    mo: 'Missouri',
    mt: 'Montana',
    ne: 'Nebraska',
    nv: 'Nevada',
    nh: 'New Hampshire',
    nj: 'New Jersey',
    nm: 'New Mexico',
    ny: 'New York',
    nc: 'North Carolina',
    nd: 'North Dakota',
    oh: 'Ohio',
    ok: 'Oklahoma',
    or: 'Oregon',
    pa: 'Pennsylvania',
    ri: 'Rhode Island',
    sc: 'South Carolina',
    sd: 'South Dakota',
    tn: 'Tennesse',
    tx: 'Texas',
    ut: 'Utah',
    vt: 'Vermont',
    va: 'Virginia',
    wa: 'Washington',
    wv: 'West Virginia',
    wi: 'Wisconsin',
    wy: 'Wyoming',
    as: 'American Samoa',
    gu: 'Guam',
    mp: 'Northern Mariana Islands',
    pr: 'Puerto Rico',
    vi: 'U.S. Virgin Islands',
    um: 'U.S. Minor Outlying Islands',
    fm: 'Micronesia',
    mh: 'Marshall Islands',
    pw: 'Palau',
}